apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: core-gateway-hpa
  namespace: backend
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: core-gateway
  minReplicas: 1
  maxReplicas: 1

  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70