apiVersion: batch/v1
kind: CronJob
metadata:
  name: batch-order-every-2-minutes
  namespace: backend
spec:
  schedule: "*/2 * * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 5
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: batch-order
              #image: ghcr.io/cloud2scape/batch-order:latest
              image: docker.io/laigasus/batch-order:latest
              imagePullPolicy: IfNotPresent
              envFrom:
                - configMapRef:
                    name: config-batch-order
              env:
                - name: "JOB_NAME"
                  value: "cancelOrderWhereStateIsPendingJob"
          restartPolicy: OnFailure
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: batch-order-every-5-minutes
  namespace: backend
spec:
  schedule: "*/5 * * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 5
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: batch-order
              #image: ghcr.io/cloud2scape/batch-order:latest
              image: docker.io/laigasus/batch-order:latest
              imagePullPolicy: IfNotPresent
              envFrom:
                - configMapRef:
                    name: config-batch-order
              env:
                - name: "JOB_NAME"
                  value: "deleteOrderWhereStateIsCanceledJob"
          restartPolicy: OnFailure