apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: service-order-hpa
  namespace: backend
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: service-order
  minReplicas: 1
  maxReplicas: 1

  metrics:
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 90