apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: purchase
  namespace: backend
  labels:
    strimzi.io/cluster: market-message
spec:
  partitions: 1
  replicas: 1
  config:
    retention.ms: 7200000
    segment.bytes: 1073741824